import React, { useState } from 'react'
const Home = () => {
  return (
    <div className=''>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
         <div className="">Home</div>
    </div>
  )
}

export default Home
